import type { FAQDTO } from './faq.dto';

export const FAQ_DATA: FAQDTO[] = [
  {
    id: 100,
    question: '주문 완료 후 결제 수단을 변경할 수 있나요?',
    answer:
      '결제 완료 이후에는 결제 수단 변경이 어렵습니다. 주문을 취소한 뒤 다시 결제해 주세요.',
    category: 'order',
    tag: '결제',
  },
  {
    id: 99,
    question: '결제 영수증은 어디에서 확인하나요?',
    answer: '마이페이지 > 주문내역에서 결제 영수증을 확인할 수 있습니다.',
    category: 'order',
    tag: '영수증',
  },
  {
    id: 98,
    question: '무통장 입금 시 입금 기한은 얼마인가요?',
    answer: '주문 후 24시간 이내에 입금해 주셔야 주문이 유지됩니다.',
    category: 'order',
    tag: '입금',
  },
  {
    id: 97,
    question: '부분 취소가 가능한가요?',
    answer: '출고 전 상태라면 일부 상품만 취소할 수 있습니다.',
    category: 'order',
    tag: '취소',
  },
  {
    id: 96,
    question: '주문 내역이 보이지 않아요.',
    answer: '비회원 주문은 비회원 주문조회에서 확인해 주세요.',
    category: 'order',
    tag: '주문조회',
  },
  {
    id: 95,
    question: '배송지는 언제까지 변경할 수 있나요?',
    answer: '출고 준비 전 단계에서만 배송지 변경이 가능합니다.',
    category: 'order',
    tag: '배송지',
  },
  {
    id: 94,
    question: '쿠폰은 주문 단계에서만 적용되나요?',
    answer: '쿠폰은 결제 단계에서 적용할 수 있습니다.',
    category: 'order',
    tag: '쿠폰',
  },
  {
    id: 93,
    question: '주문 완료 후 주소를 잘못 입력했어요.',
    answer: '출고 전이라면 고객센터로 연락해 주세요.',
    category: 'order',
    tag: '주소',
  },
  {
    id: 92,
    question: '결제 실패 시 주문은 자동 취소되나요?',
    answer: '결제가 실패하면 주문이 자동으로 취소됩니다.',
    category: 'order',
    tag: '결제실패',
  },
  {
    id: 91,
    question: '주문 후 배송 요청사항을 수정할 수 있나요?',
    answer: '출고 전이라면 고객센터를 통해 수정 가능합니다.',
    category: 'order',
    tag: '요청사항',
  },
  {
    id: 90,
    question: '배송은 얼마나 걸리나요?',
    answer: '결제 완료 후 영업일 기준 2~3일 내에 출고됩니다.',
    category: 'delivery',
    tag: '배송기간',
  },
  {
    id: 89,
    question: '토요일에도 배송이 되나요?',
    answer: '지역 및 택배사 사정에 따라 토요일 배송이 가능합니다.',
    category: 'delivery',
    tag: '토요일배송',
  },
  {
    id: 88,
    question: '배송비는 얼마인가요?',
    answer: '기본 배송비는 3,000원이며, 일정 금액 이상 구매 시 무료입니다.',
    category: 'delivery',
    tag: '배송비',
  },
  {
    id: 87,
    question: '제주/도서 지역 추가 배송비가 있나요?',
    answer: '일부 지역은 추가 배송비가 발생할 수 있습니다.',
    category: 'delivery',
    tag: '추가배송비',
  },
  {
    id: 86,
    question: '배송 조회는 어디서 하나요?',
    answer: '마이페이지 > 주문내역에서 운송장 번호를 확인하세요.',
    category: 'delivery',
    tag: '배송조회',
  },
  {
    id: 85,
    question: '배송이 지연될 때는 어떻게 알 수 있나요?',
    answer: '공지사항 및 문자 알림으로 안내드립니다.',
    category: 'delivery',
    tag: '배송지연',
  },
  {
    id: 84,
    question: '부분 배송이 가능한가요?',
    answer: '상품 준비 상황에 따라 부분 배송될 수 있습니다.',
    category: 'delivery',
    tag: '부분배송',
  },
  {
    id: 83,
    question: '해외 배송도 지원하나요?',
    answer: '현재는 국내 배송만 지원합니다.',
    category: 'delivery',
    tag: '해외배송',
  },
  {
    id: 82,
    question: '배송지가 2곳인데 나눠서 받을 수 있나요?',
    answer: '주문 건별로 1개 배송지만 지정할 수 있습니다.',
    category: 'delivery',
    tag: '배송지',
  },
  {
    id: 81,
    question: '당일 출고 가능한가요?',
    answer: '평일 오전 주문 건은 당일 출고될 수 있습니다.',
    category: 'delivery',
    tag: '당일출고',
  },
  {
    id: 80,
    question: '사이즈는 어떻게 고르나요?',
    answer: '상품 상세 페이지의 사이즈 가이드를 참고해 주세요.',
    category: 'size',
    tag: '사이즈',
  },
  {
    id: 79,
    question: '모델 착용 사이즈는 어디에 표시되나요?',
    answer: '상품 상세 설명에 모델 정보와 착용 사이즈가 표시됩니다.',
    category: 'size',
    tag: '모델',
  },
  {
    id: 78,
    question: '기장 수선이 가능한가요?',
    answer: '현재는 수선 서비스를 제공하지 않습니다.',
    category: 'size',
    tag: '수선',
  },
  {
    id: 77,
    question: '사이즈 교환은 어떻게 하나요?',
    answer: '반품 접수 후 재주문 방식으로 진행해 주세요.',
    category: 'size',
    tag: '교환',
  },
  {
    id: 76,
    question: '사이즈 상담을 받을 수 있나요?',
    answer: '고객센터로 문의 주시면 안내해 드립니다.',
    category: 'size',
    tag: '상담',
  },
  {
    id: 75,
    question: '오버핏/슬림핏 기준이 있나요?',
    answer: '상품 상세 페이지의 핏 안내를 확인해 주세요.',
    category: 'size',
    tag: '핏',
  },
  {
    id: 74,
    question: '사이즈 표기가 다르게 느껴져요.',
    answer: '측정 위치에 따라 1~2cm 오차가 있을 수 있습니다.',
    category: 'size',
    tag: '오차',
  },
  {
    id: 73,
    question: '키와 몸무게에 맞는 추천 사이즈가 있나요?',
    answer: '평소 착용 사이즈를 기준으로 선택해 주세요.',
    category: 'size',
    tag: '추천',
  },
  {
    id: 72,
    question: '아이템별 사이즈가 다른가요?',
    answer: '아이템별로 핏이 다를 수 있어 상세 사이즈 확인이 필요합니다.',
    category: 'size',
    tag: '아이템',
  },
  {
    id: 71,
    question: '사이즈 품절 시 재입고 알림이 있나요?',
    answer: '재입고 알림 신청 기능을 제공하고 있습니다.',
    category: 'size',
    tag: '재입고',
  },
  {
    id: 70,
    question: '반품 신청은 어떻게 하나요?',
    answer: '마이페이지 > 주문내역에서 반품 신청을 진행할 수 있습니다.',
    category: 'returns',
    tag: '반품',
  },
  {
    id: 69,
    question: '교환 신청도 가능한가요?',
    answer: '교환은 반품 후 재주문 방식으로 진행됩니다.',
    category: 'returns',
    tag: '교환',
  },
  {
    id: 68,
    question: '반품 배송비는 누가 부담하나요?',
    answer: '단순 변심은 고객 부담이며, 상품 불량은 무상 처리됩니다.',
    category: 'returns',
    tag: '배송비',
  },
  {
    id: 67,
    question: '환불은 언제 처리되나요?',
    answer: '반품 상품 도착 후 3~5영업일 내 환불됩니다.',
    category: 'returns',
    tag: '환불',
  },
  {
    id: 66,
    question: '반품 불가한 경우는 무엇인가요?',
    answer: '착용 흔적이 있거나 택이 제거된 상품은 반품이 불가합니다.',
    category: 'returns',
    tag: '불가',
  },
  {
    id: 65,
    question: '부분 반품이 가능한가요?',
    answer: '동일 주문 내에서도 부분 반품이 가능합니다.',
    category: 'returns',
    tag: '부분반품',
  },
  {
    id: 64,
    question: '반품 접수 후 취소할 수 있나요?',
    answer: '상품 수거 전이라면 반품 접수 취소가 가능합니다.',
    category: 'returns',
    tag: '취소',
  },
  {
    id: 63,
    question: '교환 배송비는 얼마인가요?',
    answer: '교환 배송비는 왕복 배송비가 발생할 수 있습니다.',
    category: 'returns',
    tag: '교환배송비',
  },
  {
    id: 62,
    question: '환불 수단을 변경할 수 있나요?',
    answer: '환불 수단은 결제 수단과 동일합니다.',
    category: 'returns',
    tag: '환불수단',
  },
  {
    id: 61,
    question: '교환 상품이 품절일 때는 어떻게 하나요?',
    answer: '품절인 경우 환불로 처리됩니다.',
    category: 'returns',
    tag: '품절',
  },
  {
    id: 60,
    question: '상품 정보는 어디에서 확인하나요?',
    answer: '상품 상세 페이지에서 소재, 세탁, 핏 정보를 확인할 수 있습니다.',
    category: 'product',
    tag: '상품정보',
  },
  {
    id: 59,
    question: '상품의 색상은 실제와 다른가요?',
    answer: '모니터 해상도에 따라 색상 차이가 있을 수 있습니다.',
    category: 'product',
    tag: '색상',
  },
  {
    id: 58,
    question: '세탁 방법이 궁금해요.',
    answer: '상품 상세 페이지의 세탁 안내를 확인해 주세요.',
    category: 'product',
    tag: '세탁',
  },
  {
    id: 57,
    question: '재입고 일정은 어떻게 알 수 있나요?',
    answer: '재입고 알림 신청 후 안내를 받아보실 수 있습니다.',
    category: 'product',
    tag: '재입고',
  },
  {
    id: 56,
    question: '상품 리뷰는 어디서 볼 수 있나요?',
    answer: '상품 상세 페이지 하단의 리뷰 탭에서 확인 가능합니다.',
    category: 'product',
    tag: '리뷰',
  },
  {
    id: 55,
    question: '상품 옵션 변경이 가능한가요?',
    answer: '주문 완료 이후 옵션 변경은 어렵습니다.',
    category: 'product',
    tag: '옵션',
  },
  {
    id: 54,
    question: '상품 품절 시 재입고는 언제인가요?',
    answer: '입고 일정은 상품마다 다르며 알림으로 안내됩니다.',
    category: 'product',
    tag: '품절',
  },
  {
    id: 53,
    question: '세트 상품은 개별 구매가 가능한가요?',
    answer: '세트 상품은 구성품 기준으로 판매됩니다.',
    category: 'product',
    tag: '세트',
  },
  {
    id: 52,
    question: '상품 문의는 어디에서 하나요?',
    answer: '상품 페이지의 문의하기를 이용해 주세요.',
    category: 'product',
    tag: '문의',
  },
  {
    id: 51,
    question: '상품 이미지가 실제와 다를 수 있나요?',
    answer: '촬영 환경에 따라 실제 색감과 차이가 있을 수 있습니다.',
    category: 'product',
    tag: '이미지',
  },
  {
    id: 50,
    question: '회원 가입은 어떻게 하나요?',
    answer: '로그인 페이지에서 회원가입 버튼을 눌러 진행할 수 있습니다.',
    category: 'account',
    tag: '회원가입',
  },
  {
    id: 49,
    question: '이메일/비밀번호를 잊어버렸어요.',
    answer: '로그인 화면의 비밀번호 찾기를 이용해 주세요.',
    category: 'account',
    tag: '계정찾기',
  },
  {
    id: 48,
    question: '회원 정보는 어디서 수정하나요?',
    answer: '마이페이지 > 회원정보에서 수정 가능합니다.',
    category: 'account',
    tag: '회원정보',
  },
  {
    id: 47,
    question: '비회원 주문이 가능한가요?',
    answer: '비회원 주문이 가능하지만 주문 조회는 제한될 수 있습니다.',
    category: 'account',
    tag: '비회원',
  },
  {
    id: 46,
    question: '회원 탈퇴는 어디서 하나요?',
    answer: '마이페이지 > 회원정보에서 탈퇴할 수 있습니다.',
    category: 'account',
    tag: '회원탈퇴',
  },
  {
    id: 45,
    question: '이메일 인증을 하지 않으면 주문이 불가한가요?',
    answer: '일부 서비스 이용 시 이메일 인증이 필요할 수 있습니다.',
    category: 'account',
    tag: '이메일',
  },
  {
    id: 44,
    question: '로그인 오류가 발생해요.',
    answer: '이메일/비밀번호를 확인한 뒤 다시 시도해 주세요.',
    category: 'account',
    tag: '로그인',
  },
  {
    id: 43,
    question: '비밀번호 변경은 어떻게 하나요?',
    answer: '마이페이지 > 회원정보에서 비밀번호를 변경할 수 있습니다.',
    category: 'account',
    tag: '비밀번호',
  },
  {
    id: 42,
    question: '휴면 계정은 어떻게 해제하나요?',
    answer: '고객센터에 문의해 휴면 해제를 요청해 주세요.',
    category: 'account',
    tag: '휴면',
  },
  {
    id: 41,
    question: '알림 설정은 어디서 변경하나요?',
    answer: '마이페이지의 알림 설정에서 변경할 수 있습니다.',
    category: 'account',
    tag: '알림',
  },
  {
    id: 40,
    question: '카드 결제 오류가 발생했어요.',
    answer: '카드사 문제일 수 있으니 카드사로 문의해 주세요.',
    category: 'order',
    tag: '카드결제',
  },
  {
    id: 39,
    question: '현금영수증 발급이 가능한가요?',
    answer: '무통장 입금 시 현금영수증 발급이 가능합니다.',
    category: 'order',
    tag: '현금영수증',
  },
  {
    id: 38,
    question: '결제 수단은 어떤 것이 있나요?',
    answer: '카드, 간편결제, 무통장 입금이 가능합니다.',
    category: 'order',
    tag: '결제수단',
  },
  {
    id: 37,
    question: '배송 출발 알림을 받을 수 있나요?',
    answer: '출고 시 문자로 운송장 번호가 안내됩니다.',
    category: 'delivery',
    tag: '출고알림',
  },
  {
    id: 36,
    question: '배송 시간 지정이 가능한가요?',
    answer: '택배사 정책상 시간 지정 배송은 지원하지 않습니다.',
    category: 'delivery',
    tag: '배송시간',
  },
  {
    id: 35,
    question: '사이즈 교환 시 재고는 어떻게 되나요?',
    answer: '교환 요청 시점의 재고 상황에 따라 진행됩니다.',
    category: 'size',
    tag: '재고',
  },
  {
    id: 34,
    question: '세탁 시 변형이 생기면 교환 가능한가요?',
    answer: '세탁 부주의로 인한 변형은 교환/환불이 어렵습니다.',
    category: 'returns',
    tag: '세탁',
  },
  {
    id: 33,
    question: '상품 하자 기준은 무엇인가요?',
    answer: '봉제 불량, 오염 등 사용 전 발견되는 하자는 교환 가능합니다.',
    category: 'product',
    tag: '하자',
  },
  {
    id: 32,
    question: '회원 등급 혜택은 어디서 보나요?',
    answer: '마이페이지에서 회원 등급 및 혜택을 확인할 수 있습니다.',
    category: 'account',
    tag: '등급',
  },
  {
    id: 31,
    question: '간편결제 오류가 발생했어요.',
    answer: '간편결제 앱을 업데이트한 뒤 다시 시도해 주세요.',
    category: 'order',
    tag: '간편결제',
  },
  {
    id: 30,
    question: '반품 접수 후 반품 수거는 언제 진행되나요?',
    answer: '접수 후 1~3영업일 내 방문 수거됩니다.',
    category: 'returns',
    tag: '수거',
  },
  {
    id: 29,
    question: '상품 설명과 실제 제품이 다를 때는?',
    answer: '고객센터로 문의해 주시면 교환/환불을 도와드립니다.',
    category: 'product',
    tag: '설명',
  },
  {
    id: 28,
    question: '비밀번호 재설정 이메일이 오지 않아요.',
    answer: '스팸함을 확인 후에도 없으면 고객센터로 문의해 주세요.',
    category: 'account',
    tag: '이메일',
  },
  {
    id: 27,
    question: '주문 취소 후 쿠폰은 복구되나요?',
    answer: '유효 기간 내 쿠폰은 자동 복구됩니다.',
    category: 'order',
    tag: '쿠폰복구',
  },
  {
    id: 26,
    question: '배송지 변경을 여러 번 할 수 있나요?',
    answer: '출고 전이라면 제한 없이 변경 가능합니다.',
    category: 'delivery',
    tag: '배송지',
  },
  {
    id: 25,
    question: '사이즈 교환 시 배송비는 얼마인가요?',
    answer: '왕복 배송비가 발생할 수 있습니다.',
    category: 'size',
    tag: '배송비',
  },
  {
    id: 24,
    question: '반품 접수 후 상품을 직접 보내도 되나요?',
    answer: '지정 택배사를 이용해 주셔야 합니다.',
    category: 'returns',
    tag: '택배사',
  },
  {
    id: 23,
    question: '상품 옵션이 품절되면 다른 옵션으로 변경되나요?',
    answer: '품절 시 다른 옵션으로 자동 변경되지 않습니다.',
    category: 'product',
    tag: '옵션',
  },
  {
    id: 22,
    question: '회원 가입 시 인증이 필요한가요?',
    answer: '이메일 인증을 완료해야 회원가입이 완료됩니다.',
    category: 'account',
    tag: '인증',
  },
  {
    id: 21,
    question: '주문 후 배송지 변경은 어떻게 하나요?',
    answer: '고객센터로 문의해 주시면 확인 후 변경해 드립니다.',
    category: 'order',
    tag: '배송지',
  },
  {
    id: 20,
    question: '배송 완료 후에도 배송 상태가 변하지 않아요.',
    answer: '택배사 시스템 반영까지 시간이 걸릴 수 있습니다.',
    category: 'delivery',
    tag: '배송상태',
  },
  {
    id: 19,
    question: '사이즈가 맞지 않으면 반품 가능한가요?',
    answer: '단순 변심으로 반품 가능하며 배송비는 고객 부담입니다.',
    category: 'returns',
    tag: '사이즈',
  },
  {
    id: 18,
    question: '상품 재입고 알림은 어디서 설정하나요?',
    answer: '상품 상세 페이지에서 재입고 알림을 설정할 수 있습니다.',
    category: 'product',
    tag: '재입고',
  },
  {
    id: 17,
    question: '로그인 정보를 변경할 수 있나요?',
    answer: '이메일은 변경할 수 없고 비밀번호만 변경 가능합니다.',
    category: 'account',
    tag: '로그인',
  },
  {
    id: 16,
    question: '주문이 자동 취소되는 경우가 있나요?',
    answer: '입금 기한 초과 시 주문이 자동 취소됩니다.',
    category: 'order',
    tag: '자동취소',
  },
  {
    id: 15,
    question: '배송을 빨리 받고 싶어요.',
    answer: '현재는 특급 배송 옵션을 제공하지 않습니다.',
    category: 'delivery',
    tag: '특급',
  },
  {
    id: 14,
    question: '사이즈 측정 기준이 궁금해요.',
    answer: '상품 상세 페이지의 측정 기준을 확인해 주세요.',
    category: 'size',
    tag: '측정',
  },
  {
    id: 13,
    question: '반품 상품 검수는 어떻게 진행되나요?',
    answer: '상품 도착 후 훼손 여부를 확인합니다.',
    category: 'returns',
    tag: '검수',
  },
  {
    id: 12,
    question: '상품 구성품이 누락되었어요.',
    answer: '고객센터로 연락해 주시면 신속히 처리해 드립니다.',
    category: 'product',
    tag: '구성품',
  },
  {
    id: 11,
    question: '회원 탈퇴 후 재가입이 가능한가요?',
    answer: '탈퇴 후 7일 이후 재가입이 가능합니다.',
    category: 'account',
    tag: '재가입',
  },
  {
    id: 10,
    question: '할부 결제가 가능한가요?',
    answer: '카드사 정책에 따라 할부 결제가 가능합니다.',
    category: 'order',
    tag: '할부',
  },
  {
    id: 9,
    question: '택배 분실 시 어떻게 하나요?',
    answer: '고객센터로 문의하면 택배사 확인 후 처리됩니다.',
    category: 'delivery',
    tag: '분실',
  },
  {
    id: 8,
    question: '사이즈가 커서 수선하고 싶어요.',
    answer: '수선 서비스는 제공하지 않습니다.',
    category: 'size',
    tag: '수선',
  },
  {
    id: 7,
    question: '환불이 지연될 때는 어떻게 하나요?',
    answer: '고객센터로 문의해 주시면 확인 후 안내해 드립니다.',
    category: 'returns',
    tag: '지연',
  },
  {
    id: 6,
    question: '상품 리뷰 작성은 어디서 하나요?',
    answer: '마이페이지 > 주문내역에서 리뷰를 작성할 수 있습니다.',
    category: 'product',
    tag: '리뷰작성',
  },
  {
    id: 5,
    question: '개인정보 수정은 어디서 하나요?',
    answer: '마이페이지 > 회원정보에서 수정 가능합니다.',
    category: 'account',
    tag: '개인정보',
  },
  {
    id: 4,
    question: '세금계산서 발급이 가능한가요?',
    answer: '사업자 회원에 한해 발급 가능합니다.',
    category: 'order',
    tag: '세금계산서',
  },
  {
    id: 3,
    question: '수취인 연락이 되지 않아 반송되었어요.',
    answer: '고객센터로 연락해 재배송을 요청해 주세요.',
    category: 'delivery',
    tag: '반송',
  },
  {
    id: 2,
    question: '상품 불량 교환은 어떻게 하나요?',
    answer: '상품 수령 후 7일 이내 교환 신청이 가능합니다.',
    category: 'returns',
    tag: '불량',
  },
  {
    id: 1,
    question: '회원 탈퇴 시 적립금은 어떻게 되나요?',
    answer: '탈퇴 시 보유 적립금은 소멸됩니다.',
    category: 'account',
    tag: '적립금',
  },
];
