import type { NoticeDTO } from './notice.dto';

export const NOTICES: NoticeDTO[] = [
  {
    id: 100,
    title: '주말 배송 지연 안내',
    date: '2026.03.05',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 99,
    title: '물류센터 시스템 점검 안내',
    date: '2026.03.04',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 98,
    title: '결제 시스템 정기 점검 안내',
    date: '2026.03.03',
    category: 'system',
    tag: '점검',
  },
  {
    id: 97,
    title: '모바일 앱 기능 개선 안내',
    date: '2026.03.02',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 96,
    title: '고객센터 운영 시간 변경 안내',
    date: '2026.03.01',
    category: 'policy',
    tag: '서비스',
  },
  {
    id: 95,
    title: '개인정보 처리방침 개정 안내',
    date: '2026.02.28',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 94,
    title: '2월 리뷰 이벤트 당첨자 발표',
    date: '2026.02.27',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 93,
    title: '일부 지역 배송 지연 안내',
    date: '2026.02.26',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 92,
    title: '설 연휴 출고 마감 일정 안내',
    date: '2026.02.25',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 91,
    title: '쇼핑몰 서버 점검 안내',
    date: '2026.02.24',
    category: 'system',
    tag: '점검',
  },
  {
    id: 90,
    title: '검색 기능 개선 안내',
    date: '2026.02.23',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 89,
    title: '1:1 문의 답변 지연 안내',
    date: '2026.02.22',
    category: 'policy',
    tag: '서비스',
  },
  {
    id: 88,
    title: '교환·반품 정책 변경 안내',
    date: '2026.02.21',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 87,
    title: '신년 기획전 당첨자 발표',
    date: '2026.02.20',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 86,
    title: '택배사 파업 관련 안내',
    date: '2026.02.19',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 85,
    title: '물류센터 재고 조정 안내',
    date: '2026.02.18',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 84,
    title: '야간 네트워크 점검 안내',
    date: '2026.02.17',
    category: 'system',
    tag: '점검',
  },
  {
    id: 83,
    title: '결제 페이지 UI 개선 안내',
    date: '2026.02.16',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 82,
    title: '고객 만족도 조사 안내',
    date: '2026.02.15',
    category: 'policy',
    tag: '서비스',
  },
  {
    id: 81,
    title: '이용 약관 개정 안내',
    date: '2026.02.14',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 80,
    title: '발렌타인 이벤트 당첨자 발표',
    date: '2026.02.13',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 79,
    title: '당일 배송 지역 확대 안내',
    date: '2026.02.12',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 78,
    title: '입고 지연 상품 안내',
    date: '2026.02.11',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 77,
    title: '주문 시스템 점검 안내',
    date: '2026.02.10',
    category: 'system',
    tag: '점검',
  },
  {
    id: 76,
    title: '마이페이지 기능 개선 안내',
    date: '2026.02.09',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 75,
    title: '고객센터 전화 회선 증설 안내',
    date: '2026.02.08',
    category: 'policy',
    tag: '서비스',
  },
  {
    id: 74,
    title: '배송비 정책 변경 안내',
    date: '2026.02.07',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 73,
    title: '설날 쿠폰 이벤트 당첨자 발표',
    date: '2026.02.06',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 72,
    title: '새벽 배송 일시 중단 안내',
    date: '2026.02.05',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 71,
    title: '물류센터 휴무 일정 안내',
    date: '2026.02.04',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 70,
    title: '재고 시스템 점검 안내',
    date: '2026.02.03',
    category: 'system',
    tag: '점검',
  },
  {
    id: 69,
    title: '리뷰 작성 기능 개선 안내',
    date: '2026.02.02',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 68,
    title: '챗봇 상담 서비스 오픈 안내',
    date: '2026.02.01',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 67,
    title: '멤버십 등급 정책 변경 안내',
    date: '2026.01.31',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 66,
    title: '1월 출석 이벤트 당첨자 발표',
    date: '2026.01.30',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 65,
    title: '해외 배송 일정 안내',
    date: '2026.01.29',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 64,
    title: '상품 재입고 일정 안내',
    date: '2026.01.28',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 63,
    title: '회원 시스템 점검 안내',
    date: '2026.01.27',
    category: 'system',
    tag: '점검',
  },
  {
    id: 62,
    title: '상품 상세 페이지 개선 안내',
    date: '2026.01.26',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 61,
    title: '상담원 연결 지연 안내',
    date: '2026.01.25',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 60,
    title: '쿠폰 사용 정책 변경 안내',
    date: '2026.01.24',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 59,
    title: '겨울 세일 이벤트 당첨자 발표',
    date: '2026.01.23',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 58,
    title: '눈/비로 인한 배송 지연 안내',
    date: '2026.01.22',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 57,
    title: '물류센터 이전 일정 안내',
    date: '2026.01.21',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 56,
    title: '쿠폰 시스템 점검 안내',
    date: '2026.01.20',
    category: 'system',
    tag: '점검',
  },
  {
    id: 55,
    title: '장바구니 기능 개선 안내',
    date: '2026.01.19',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 54,
    title: '서비스 만족도 설문 안내',
    date: '2026.01.18',
    category: 'policy',
    tag: '서비스',
  },
  {
    id: 53,
    title: '포인트 적립 정책 변경 안내',
    date: '2026.01.17',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 52,
    title: '신년 첫 구매 이벤트 당첨자 발표',
    date: '2026.01.16',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 51,
    title: '제주/도서 지역 배송 안내',
    date: '2026.01.15',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 50,
    title: '출고 지연 상품 안내',
    date: '2026.01.14',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 49,
    title: '정산 시스템 점검 안내',
    date: '2026.01.13',
    category: 'system',
    tag: '점검',
  },
  {
    id: 48,
    title: '카테고리 구조 개선 안내',
    date: '2026.01.12',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 47,
    title: '라이브 채팅 상담 오픈 안내',
    date: '2026.01.11',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 46,
    title: '환불 처리 절차 변경 안내',
    date: '2026.01.10',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 45,
    title: '크리스마스 이벤트 당첨자 발표',
    date: '2026.01.09',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 44,
    title: '연말 배송 마감 안내',
    date: '2026.01.08',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 43,
    title: '재고 조사 일정 안내',
    date: '2026.01.07',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 42,
    title: '포인트 시스템 점검 안내',
    date: '2026.01.06',
    category: 'system',
    tag: '점검',
  },
  {
    id: 41,
    title: '추천 상품 기능 개선 안내',
    date: '2026.01.05',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 40,
    title: '전화 상담 시스템 개선 안내',
    date: '2026.01.04',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 39,
    title: '회원 탈퇴 처리 변경 안내',
    date: '2026.01.03',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 38,
    title: '연말 럭키드로우 당첨자 발표',
    date: '2026.01.02',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 37,
    title: '새해 배송 일정 안내',
    date: '2026.01.01',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 36,
    title: '물류센터 운영 일정 안내',
    date: '2025.12.31',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 35,
    title: '결제 모듈 업데이트 안내',
    date: '2025.12.30',
    category: 'system',
    tag: '점검',
  },
  {
    id: 34,
    title: '주문 내역 UI 개선 안내',
    date: '2025.12.29',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 33,
    title: '연말 고객센터 운영 안내',
    date: '2025.12.28',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 32,
    title: '적립금 사용 정책 변경 안내',
    date: '2025.12.27',
    category: 'policy',
    tag: '정책',
  },
  {
    id: 31,
    title: '블랙프라이데이 당첨자 발표',
    date: '2025.12.26',
    category: 'winners',
    tag: '이벤트 당첨',
  },
  {
    id: 30,
    title: '택배사 물량 폭주 안내',
    date: '2025.12.25',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 29,
    title: '물류센터 재오픈 안내',
    date: '2025.12.24',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 28,
    title: '회원 인증 시스템 점검 안내',
    date: '2025.12.23',
    category: 'system',
    tag: '점검',
  },
  {
    id: 27,
    title: '쿠폰함 기능 개선 안내',
    date: '2025.12.22',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 26,
    title: '이메일 상담 응답 지연 안내',
    date: '2025.12.21',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 25,
    title: '배송지 변경 규정 안내',
    date: '2025.12.20',
    category: 'policy',
    tag: '정책',
  },

  {
    id: 23,
    title: '택배사 휴무 일정 안내',
    date: '2025.12.18',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 22,
    title: '입고 예정 품절 상품 안내',
    date: '2025.12.17',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 21,
    title: '주문 알림 시스템 점검 안내',
    date: '2025.12.16',
    category: 'system',
    tag: '점검',
  },
  {
    id: 20,
    title: '배송 추적 기능 개선 안내',
    date: '2025.12.15',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 19,
    title: '고객센터 점심 시간 변경 안내',
    date: '2025.12.14',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 18,
    title: '회원 등급 산정 기준 변경 안내',
    date: '2025.12.13',
    category: 'policy',
    tag: '정책',
  },
 
  {
    id: 16,
    title: '배송비 프로모션 종료 안내',
    date: '2025.12.11',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 15,
    title: '반품 물량 증가 안내',
    date: '2025.12.10',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 14,
    title: '회원 혜택 시스템 점검 안내',
    date: '2025.12.09',
    category: 'system',
    tag: '점검',
  },
  {
    id: 13,
    title: '알림 센터 UI 개선 안내',
    date: '2025.12.08',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 12,
    title: '상담 채널 통합 안내',
    date: '2025.12.07',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 11,
    title: '서비스 이용 정책 변경 안내',
    date: '2025.12.06',
    category: 'policy',
    tag: '정책',
  },

  {
    id: 9,
    title: '일부 택배사 지역 제한 안내',
    date: '2025.12.04',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 8,
    title: '창고 정리 일정 안내',
    date: '2025.12.03',
    category: 'shipping',
    tag: '물류',
  },
  {
    id: 7,
    title: '이미지 서버 점검 안내',
    date: '2025.12.02',
    category: 'system',
    tag: '점검',
  },
  {
    id: 6,
    title: '추천 검색어 기능 추가 안내',
    date: '2025.12.01',
    category: 'system',
    tag: '업데이트',
  },
  {
    id: 5,
    title: '상담 품질 개선 캠페인 안내',
    date: '2025.11.30',
    category: 'system',
    tag: '서비스',
  },
  {
    id: 4,
    title: '스팸/도배 제재 정책 안내',
    date: '2025.11.29',
    category: 'policy',
    tag: '정책',
  },

  {
    id: 2,
    title: '연말 물류 혼잡 안내',
    date: '2025.11.27',
    category: 'shipping',
    tag: '배송',
  },
  {
    id: 1,
    title: '포장재 변경 안내',
    date: '2025.11.26',
    category: 'shipping',
    tag: '물류',
  },
];
