import type { ProductDTO, ProductColorDTO } from './product.dto';

export const colorMap: ProductColorDTO[] = [
  // 1. Warm & Light (아이보리, 베이지, 카멜)
  { id: 13, label: '아이보리', hexCode: '#FFFFF0', code: 'IV' },
  { id: 18, label: '머드 베이지', hexCode: '#C2B280', code: 'MBE' },
  { id: 3, label: '카멜', hexCode: '#C19A6B', code: 'CM' },
  { id: 17, label: '다크 브라운', hexCode: '#654321', code: 'DBR' },
  { id: 12, label: '올리브 브라운', hexCode: '#556B2F', code: 'OBR' },

  // 2. Point Colors (레드, 카키, 그린)
  { id: 8, label: '레드', hexCode: '#FF0000', code: 'RD' },
  { id: 15, label: '카키', hexCode: '#F0E68C', code: 'KH' },
  { id: 9, label: '머드 카키', hexCode: '#8B4513', code: 'MK' },
  { id: 7, label: '그린', hexCode: '#008000', code: 'GN' },
  { id: 10, label: '다크 그린', hexCode: '#006400', code: 'DGN' },

  // 3. Cool & Deep (네이비)
  { id: 4, label: '네이비', hexCode: '#000080', code: 'NV' },

  // 4. Achromatic (화이트/그레이 계열 -> 블랙)
  { id: 11, label: '멜란지 그레이', hexCode: '#B0C4DE', code: 'MGY' },
  { id: 19, label: '그레이 믹스', hexCode: '#BEBEBE', code: 'GMX' },
  { id: 1, label: '그레이', hexCode: '#808080', code: 'GY' },
  { id: 6, label: '카키 그레이', hexCode: '#BDB76B', code: 'KGY' },
  { id: 5, label: '다크 그레이', hexCode: '#A9A9A9', code: 'DGY' },
  { id: 16, label: '차콜', hexCode: '#36454F', code: 'CH' },
  { id: 2, label: '다크', hexCode: '#333333', code: 'DK' },
  { id: 14, label: '블랙', hexCode: '#000000', code: 'BK' },
];

export const products: ProductDTO[] = [
  {
    id: 1,
    group_id: 1,
    name: '그레이 싱글 체스터필드 코트',
    colorId: 1,
    category: { parent: 'outer', current: 'coat' },
    price: 289000,
    thumbnailImage: 'Coat-1.png',
    detailImages: ['Coat-1.png', 'Coat-1-1.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '1-GY-S', size: 'S', stock: 12, price_offset: 0 },
      { id: '1-GY-M', size: 'M', stock: 18, price_offset: 0 },
      { id: '1-GY-L', size: 'L', stock: 5, price_offset: 0 },
      { id: '1-GY-XL', size: 'XL', stock: 3, price_offset: 5000 },
      { id: '1-GY-2XL', size: '2XL', stock: 0, price_offset: 10000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 2451,
      toDaySales: 12,
      weeklySales: 89,
      monthlySales: 342,
    },
  },
  {
    id: 2,
    group_id: 1,
    name: '다크 싱글 체스터필드 코트',
    colorId: 2,
    category: { parent: 'outer', current: 'coat' },
    price: 289000,
    thumbnailImage: 'Coat-1-2.png',
    detailImages: ['Coat-1-2.png', 'Coat-1-3.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '1-DK-S', size: 'S', stock: 8, price_offset: 0 },
      { id: '1-DK-M', size: 'M', stock: 10, price_offset: 0 },
      { id: '1-DK-L', size: 'L', stock: 15, price_offset: 0 },
      { id: '1-DK-XL', size: 'XL', stock: 2, price_offset: 5000 },
      { id: '1-DK-2XL', size: '2XL', stock: 4, price_offset: 10000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 892,
      toDaySales: 3,
      weeklySales: 42,
      monthlySales: 156,
    },
  },
  {
    id: 3,
    group_id: 1,
    name: '카멜 싱글 체스터필드 코트',
    colorId: 3,
    category: { parent: 'outer', current: 'coat' },
    price: 289000,
    thumbnailImage: 'Coat-1-4.png',
    detailImages: ['Coat-1-4.png', 'Coat-1-5.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '1-CM-S', size: 'S', stock: 20, price_offset: 0 },
      { id: '1-CM-M', size: 'M', stock: 12, price_offset: 0 },
      { id: '1-CM-L', size: 'L', stock: 7, price_offset: 0 },
      { id: '1-CM-XL', size: 'XL', stock: 0, price_offset: 5000 },
      { id: '1-CM-2XL', size: '2XL', stock: 1, price_offset: 10000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1567,
      toDaySales: 21,
      weeklySales: 112,
      monthlySales: 489,
    },
  },
  {
    id: 4,
    group_id: 2,
    name: '카멜 더블 브레스트 롱 코트',
    colorId: 3,
    category: { parent: 'outer', current: 'coat' },
    price: 320000,
    thumbnailImage: 'Coat-2.png',
    detailImages: ['Coat-2.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '2-CM-S', size: 'S', stock: 5, price_offset: 0 },
      { id: '2-CM-M', size: 'M', stock: 3, price_offset: 0 },
      { id: '2-CM-L', size: 'L', stock: 10, price_offset: 0 },
      { id: '2-CM-XL', size: 'XL', stock: 4, price_offset: 7000 },
      { id: '2-CM-2XL', size: '2XL', stock: 2, price_offset: 14000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 432,
      toDaySales: 0,
      weeklySales: 28,
      monthlySales: 92,
    },
  },
  {
    id: 5,
    group_id: 3,
    name: '네이비 히든 버튼 스탠드 칼라 코트',
    colorId: 4,
    category: { parent: 'outer', current: 'coat' },
    price: 255000,
    thumbnailImage: 'Coat-3.png',
    detailImages: ['Coat-3.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '3-NV-S', size: 'S', stock: 10, price_offset: 0 },
      { id: '3-NV-M', size: 'M', stock: 8, price_offset: 0 },
      { id: '3-NV-L', size: 'L', stock: 6, price_offset: 0 },
      { id: '3-NV-XL', size: 'XL', stock: 4, price_offset: 5000 },
      { id: '3-NV-2XL', size: '2XL', stock: 2, price_offset: 10000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 2840,
      toDaySales: 28,
      weeklySales: 167,
      monthlySales: 512,
    },
  },
  {
    id: 6,
    group_id: 4,
    name: '다크 그레이 더블 피코트',
    colorId: 5,
    category: { parent: 'outer', current: 'coat' },
    price: 210000,
    thumbnailImage: 'Coat-4.png',
    detailImages: ['Coat-4.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '4-DGY-S', size: 'S', stock: 0, price_offset: 0 },
      { id: '4-DGY-M', size: 'M', stock: 0, price_offset: 0 },
      { id: '4-DGY-L', size: 'L', stock: 0, price_offset: 0 },
      { id: '4-DGY-XL', size: 'XL', stock: 0, price_offset: 5000 },
      { id: '4-DGY-2XL', size: '2XL', stock: 0, price_offset: 10000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 621,
      toDaySales: 1,
      weeklySales: 15,
      monthlySales: 102,
    },
  },
  {
    id: 7,
    group_id: 5,
    name: '카키 그레이 립조직 블루종 자켓',
    colorId: 6,
    category: { parent: 'outer', current: 'jacket' },
    price: 159000,
    thumbnailImage: 'jacket-1.png',
    detailImages: ['jacket-1.png'],
    createdAt: new Date('2026-04-02'),
    variants: [
      { id: '5-KGY-S', size: 'S', stock: 10, price_offset: 0 },
      { id: '5-KGY-M', size: 'M', stock: 15, price_offset: 0 },
      { id: '5-KGY-L', size: 'L', stock: 12, price_offset: 0 },
      { id: '5-KGY-XL', size: 'XL', stock: 8, price_offset: 3000 },
      { id: '5-KGY-2XL', size: '2XL', stock: 4, price_offset: 6000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1842,
      toDaySales: 15,
      weeklySales: 94,
      monthlySales: 412,
    },
  },
  {
    id: 8,
    group_id: 6,
    name: '네이비 M-65 필드 유틸리티 자켓',
    colorId: 4,
    category: { parent: 'outer', current: 'jacket' },
    price: 189000,
    thumbnailImage: 'jacket-2.png',
    detailImages: ['jacket-2.png'],
    createdAt: new Date('2026-04-02'),
    variants: [
      { id: '6-NV-S', size: 'S', stock: 7, price_offset: 0 },
      { id: '6-NV-M', size: 'M', stock: 9, price_offset: 0 },
      { id: '6-NV-L', size: 'L', stock: 14, price_offset: 0 },
      { id: '6-NV-XL', size: 'XL', stock: 5, price_offset: 4000 },
      { id: '6-NV-2XL', size: '2XL', stock: 0, price_offset: 8000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1120,
      toDaySales: 4,
      weeklySales: 56,
      monthlySales: 215,
    },
  },
  {
    id: 9,
    group_id: 7,
    name: '그린 화이트 배색 트랙탑 자켓',
    colorId: 7,
    category: { parent: 'outer', current: 'jacket' },
    price: 89000,
    thumbnailImage: 'jacket-3.png',
    detailImages: ['jacket-3.png'],
    createdAt: new Date('2026-04-02'),
    variants: [
      { id: '7-GN-S', size: 'S', stock: 20, price_offset: 0 },
      { id: '7-GN-M', size: 'M', stock: 18, price_offset: 0 },
      { id: '7-GN-L', size: 'L', stock: 15, price_offset: 0 },
      { id: '7-GN-XL', size: 'XL', stock: 10, price_offset: 2000 },
      { id: '7-GN-2XL', size: '2XL', stock: 5, price_offset: 4000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 2134,
      toDaySales: 32,
      weeklySales: 142,
      monthlySales: 562,
    },
  },
  {
    id: 10,
    group_id: 8,
    name: '그레이 윈도우체크 테일러드 블레이저',
    colorId: 1,
    category: { parent: 'outer', current: 'jacket' },
    price: 230000,
    thumbnailImage: 'jacket-4.png',
    detailImages: ['jacket-4.png'],
    createdAt: new Date('2026-04-05'),
    variants: [
      { id: '8-GY-S', size: 'S', stock: 5, price_offset: 0 },
      { id: '8-GY-M', size: 'M', stock: 8, price_offset: 0 },
      { id: '8-GY-L', size: 'L', stock: 10, price_offset: 0 },
      { id: '8-GY-XL', size: 'XL', stock: 3, price_offset: 5000 },
      { id: '8-GY-2XL', size: '2XL', stock: 1, price_offset: 10000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 549,
      toDaySales: 2,
      weeklySales: 24,
      monthlySales: 88,
    },
  },
  {
    id: 11,
    group_id: 9,
    name: '그린 스트라이프 스포츠 저지 자켓',
    colorId: 7,
    category: { parent: 'outer', current: 'jacket' },
    price: 89000,
    thumbnailImage: 'jacket-5.png',
    detailImages: ['jacket-5.png'],
    createdAt: new Date('2026-03-22'),
    variants: [
      { id: '9-GN-S', size: 'S', stock: 0, price_offset: 0 },
      { id: '9-GN-M', size: 'M', stock: 0, price_offset: 0 },
      { id: '9-GN-L', size: 'L', stock: 0, price_offset: 0 },
      { id: '9-GN-XL', size: 'XL', stock: 0, price_offset: 2000 },
      { id: '9-GN-2XL', size: '2XL', stock: 0, price_offset: 4000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 132,
      toDaySales: 0,
      weeklySales: 5,
      monthlySales: 21,
    },
  },
  {
    id: 12,
    group_id: 10,
    name: '레드 후드 윈드브레이커 자켓',
    colorId: 8,
    category: { parent: 'outer', current: 'jacket' },
    price: 129000,
    thumbnailImage: 'jacket-6.png',
    detailImages: ['jacket-6.png'],
    createdAt: new Date('2026-03-22'),
    variants: [
      { id: '10-RD-S', size: 'S', stock: 15, price_offset: 0 },
      { id: '10-RD-M', size: 'M', stock: 11, price_offset: 0 },
      { id: '10-RD-L', size: 'L', stock: 9, price_offset: 0 },
      { id: '10-RD-XL', size: 'XL', stock: 6, price_offset: 3000 },
      { id: '10-RD-2XL', size: '2XL', stock: 3, price_offset: 6000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 954,
      toDaySales: 7,
      weeklySales: 41,
      monthlySales: 128,
    },
  },
  {
    id: 13,
    group_id: 11,
    name: '머드 카키 포켓 사파리 자켓',
    colorId: 18,
    category: { parent: 'outer', current: 'jacket' },
    price: 175000,
    thumbnailImage: 'jacket-7.png',
    detailImages: ['jacket-7.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '11-MBE-S', size: 'S', stock: 4, price_offset: 0 },
      { id: '11-MBE-M', size: 'M', stock: 7, price_offset: 0 },
      { id: '11-MBE-L', size: 'L', stock: 10, price_offset: 0 },
      { id: '11-MBE-XL', size: 'XL', stock: 2, price_offset: 4000 },
      { id: '11-MBE-2XL', size: '2XL', stock: 0, price_offset: 8000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 612,
      toDaySales: 2,
      weeklySales: 18,
      monthlySales: 76,
    },
  },
  {
    id: 14,
    group_id: 12,
    name: '다크 그린 립조직 V넥 가디건',
    colorId: 10,
    category: { parent: 'outer', current: 'cardigan' },
    price: 129000,
    thumbnailImage: 'cardigan-1.png',
    detailImages: ['cardigan-1.png'],
    createdAt: new Date('2026-03-24'),
    variants: [
      { id: '12-DGN-S', size: 'S', stock: 11, price_offset: 0 },
      { id: '12-DGN-M', size: 'M', stock: 14, price_offset: 0 },
      { id: '12-DGN-L', size: 'L', stock: 9, price_offset: 0 },
      { id: '12-DGN-XL', size: 'XL', stock: 5, price_offset: 2000 },
      { id: '12-DGN-2XL', size: '2XL', stock: 3, price_offset: 4000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1421,
      toDaySales: 11,
      weeklySales: 74,
      monthlySales: 289,
    },
  },
  {
    id: 15,
    group_id: 13,
    name: '멜란지 그레이 보일드 울 가디건',
    colorId: 11,
    category: { parent: 'outer', current: 'cardigan' },
    price: 145000,
    thumbnailImage: 'cardigan-2.png',
    detailImages: ['cardigan-2.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '13-MGY-S', size: 'S', stock: 6, price_offset: 0 },
      { id: '13-MGY-M', size: 'M', stock: 8, price_offset: 0 },
      { id: '13-MGY-L', size: 'L', stock: 12, price_offset: 0 },
      { id: '13-MGY-XL', size: 'XL', stock: 4, price_offset: 3000 },
      { id: '13-MGY-2XL', size: '2XL', stock: 1, price_offset: 6000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 782,
      toDaySales: 5,
      weeklySales: 38,
      monthlySales: 142,
    },
  },
  {
    id: 16,
    group_id: 14,
    name: '올리브 브라운 케이블 집업 가디건',
    colorId: 12,
    category: { parent: 'outer', current: 'cardigan' },
    price: 158000,
    thumbnailImage: 'cardigan-3.png',
    detailImages: ['cardigan-3.png'],
    createdAt: new Date('2026-03-24'),
    restockedAt: new Date('2026-04-10'),
    variants: [
      { id: '14-OBR-S', size: 'S', stock: 0, price_offset: 0 },
      { id: '14-OBR-M', size: 'M', stock: 0, price_offset: 0 },
      { id: '14-OBR-L', size: 'L', stock: 0, price_offset: 0 },
      { id: '14-OBR-XL', size: 'XL', stock: 0, price_offset: 3000 },
      { id: '14-OBR-2XL', size: '2XL', stock: 0, price_offset: 6000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 212,
      toDaySales: 0,
      weeklySales: 8,
      monthlySales: 45,
    },
  },
  {
    id: 17,
    group_id: 15,
    name: '네이비 클래식 숄 칼라 가디건',
    colorId: 4,
    category: { parent: 'outer', current: 'cardigan' },
    price: 139000,
    thumbnailImage: 'cardigan-4.png',
    detailImages: ['cardigan-4.png'],
    createdAt: new Date('2026-03-24'),
    restockedAt: new Date('2026-04-10'),
    variants: [
      { id: '15-NV-S', size: 'S', stock: 18, price_offset: 0 },
      { id: '15-NV-M', size: 'M', stock: 13, price_offset: 0 },
      { id: '15-NV-L', size: 'L', stock: 7, price_offset: 0 },
      { id: '15-NV-XL', size: 'XL', stock: 4, price_offset: 2500 },
      { id: '15-NV-2XL', size: '2XL', stock: 0, price_offset: 5000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1678,
      toDaySales: 14,
      weeklySales: 82,
      monthlySales: 310,
    },
  },
  {
    id: 18,
    group_id: 16,
    name: '아이보리 와플 조직 스탠드넥 집업 가디건',
    colorId: 13,
    category: { parent: 'outer', current: 'cardigan' },
    price: 142000,
    thumbnailImage: 'cardigan-5.png',
    detailImages: ['cardigan-5.png'],
    createdAt: new Date('2026-03-24'),
    restockedAt: new Date('2026-05-02'),
    variants: [
      { id: '16-IV-S', size: 'S', stock: 10, price_offset: 0 },
      { id: '16-IV-M', size: 'M', stock: 12, price_offset: 0 },
      { id: '16-IV-L', size: 'L', stock: 8, price_offset: 0 },
      { id: '16-IV-XL', size: 'XL', stock: 5, price_offset: 2500 },
      { id: '16-IV-2XL', size: '2XL', stock: 3, price_offset: 5000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1245,
      toDaySales: 9,
      weeklySales: 63,
      monthlySales: 241,
    },
  },
  {
    id: 19,
    group_id: 17,
    name: '블랙 퀄팅 후드 패딩 점퍼',
    colorId: 14,
    category: { parent: 'outer', current: 'padding' },
    price: 198000,
    thumbnailImage: 'padding-1.png',
    detailImages: ['padding-1.png'],
    createdAt: new Date('2026-05-04'),
    variants: [
      { id: '17-BK-S', size: 'S', stock: 0, price_offset: 0 },
      { id: '17-BK-M', size: 'M', stock: 0, price_offset: 0 },
      { id: '17-BK-L', size: 'L', stock: 0, price_offset: 0 },
      { id: '17-BK-XL', size: 'XL', stock: 0, price_offset: 8000 },
      { id: '17-BK-2XL', size: '2XL', stock: 0, price_offset: 15000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 3042,
      toDaySales: 5,
      weeklySales: 120,
      monthlySales: 456,
    },
  },
  {
    id: 20,
    group_id: 18,
    name: '네이비 경량 다운 패딩 조끼',
    colorId: 4,
    category: { parent: 'outer', current: 'padding' },
    price: 85000,
    thumbnailImage: 'padding-2.png',
    detailImages: ['padding-2.png'],
    createdAt: new Date('2026-04-05'),
    variants: [
      { id: '18-NV-S', size: 'S', stock: 12, price_offset: 0 },
      { id: '18-NV-M', size: 'M', stock: 18, price_offset: 0 },
      { id: '18-NV-L', size: 'L', stock: 14, price_offset: 0 },
      { id: '18-NV-XL', size: 'XL', stock: 9, price_offset: 3000 },
      { id: '18-NV-2XL', size: '2XL', stock: 5, price_offset: 6000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 2715,
      toDaySales: 24,
      weeklySales: 189,
      monthlySales: 612,
    },
  },
  {
    id: 21,
    group_id: 19,
    name: '그레이 멜란지 후드 숏패딩',
    colorId: 11,
    category: { parent: 'outer', current: 'padding' },
    price: 165000,
    thumbnailImage: 'padding-3.png',
    detailImages: ['padding-3.png'],
    createdAt: new Date('2026-04-05'),
    variants: [
      { id: '19-MGY-S', size: 'S', stock: 5, price_offset: 0 },
      { id: '19-MGY-M', size: 'M', stock: 8, price_offset: 0 },
      { id: '19-MGY-L', size: 'L', stock: 10, price_offset: 0 },
      { id: '19-MGY-XL', size: 'XL', stock: 4, price_offset: 7000 },
      { id: '19-MGY-2XL', size: '2XL', stock: 0, price_offset: 14000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1890,
      toDaySales: 17,
      weeklySales: 104,
      monthlySales: 387,
    },
  },
  {
    id: 22,
    group_id: 20,
    name: '라이트 베이지 하이넥 푸퍼 패딩',
    colorId: 18,
    category: { parent: 'outer', current: 'padding' },
    price: 179000,
    thumbnailImage: 'padding-4.png',
    detailImages: ['padding-4.png'],
    createdAt: new Date('2026-03-24'),
    variants: [
      { id: '20-MBE-S', size: 'S', stock: 8, price_offset: 0 },
      { id: '20-MBE-M', size: 'M', stock: 12, price_offset: 0 },
      { id: '20-MBE-L', size: 'L', stock: 15, price_offset: 0 },
      { id: '20-MBE-XL', size: 'XL', stock: 7, price_offset: 7000 },
      { id: '20-MBE-2XL', size: '2XL', stock: 3, price_offset: 14000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1422,
      toDaySales: 8,
      weeklySales: 71,
      monthlySales: 294,
    },
  },
  {
    id: 23,
    group_id: 21,
    name: '카키 오버사이즈 덕다운 패딩',
    colorId: 15,
    category: { parent: 'outer', current: 'padding' },
    price: 210000,
    thumbnailImage: 'padding-5.png',
    detailImages: ['padding-5.png'],
    createdAt: new Date('2026-03-24'),
    variants: [
      { id: '21-KH-S', size: 'S', stock: 4, price_offset: 0 },
      { id: '21-KH-M', size: 'M', stock: 9, price_offset: 0 },
      { id: '21-KH-L', size: 'L', stock: 11, price_offset: 0 },
      { id: '21-KH-XL', size: 'XL', stock: 5, price_offset: 8000 },
      { id: '21-KH-2XL', size: '2XL', stock: 2, price_offset: 16000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 567,
      toDaySales: 3,
      weeklySales: 22,
      monthlySales: 105,
    },
  },
  {
    id: 24,
    group_id: 22,
    name: '차콜 스탠드칼라 경량 패딩',
    colorId: 16,
    category: { parent: 'outer', current: 'padding' },
    price: 120000,
    thumbnailImage: 'padding-6.png',
    detailImages: ['padding-6.png'],
    createdAt: new Date('2026-03-24'),
    variants: [
      { id: '22-CH-S', size: 'S', stock: 15, price_offset: 0 },
      { id: '22-CH-M', size: 'M', stock: 12, price_offset: 0 },
      { id: '22-CH-L', size: 'L', stock: 10, price_offset: 0 },
      { id: '22-CH-XL', size: 'XL', stock: 6, price_offset: 4000 },
      { id: '22-CH-2XL', size: '2XL', stock: 3, price_offset: 8000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1104,
      toDaySales: 10,
      weeklySales: 58,
      monthlySales: 201,
    },
  },
  {
    id: 25,
    group_id: 23,
    name: '다크 브라운 롱 구스다운 패딩',
    colorId: 17,
    category: { parent: 'outer', current: 'padding' },
    price: 345000,
    thumbnailImage: 'padding-7.png',
    detailImages: ['padding-7.png'],
    createdAt: new Date('2026-03-24'),
    variants: [
      { id: '23-DBR-S', size: 'S', stock: 0, price_offset: 0 },
      { id: '23-DBR-M', size: 'M', stock: 0, price_offset: 0 },
      { id: '23-DBR-L', size: 'L', stock: 0, price_offset: 0 },
      { id: '23-DBR-XL', size: 'XL', stock: 0, price_offset: 12000 },
      { id: '23-DBR-2XL', size: '2XL', stock: 0, price_offset: 24000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 412,
      toDaySales: 1,
      weeklySales: 12,
      monthlySales: 58,
    },
  },
  {
    id: 26,
    group_id: 24,
    name: '머드 베이지 베이직 숏 푸퍼',
    colorId: 18,
    category: { parent: 'outer', current: 'padding' },
    price: 159000,
    thumbnailImage: 'padding-8.png',
    detailImages: ['padding-8.png'],
    createdAt: new Date('2026-04-20'),
    variants: [
      { id: '24-MBE-S', size: 'S', stock: 14, price_offset: 0 },
      { id: '24-MBE-M', size: 'M', stock: 10, price_offset: 0 },
      { id: '24-MBE-L', size: 'L', stock: 8, price_offset: 0 },
      { id: '24-MBE-XL', size: 'XL', stock: 5, price_offset: 6000 },
      { id: '24-MBE-2XL', size: '2XL', stock: 2, price_offset: 12000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 2234,
      toDaySales: 21,
      weeklySales: 145,
      monthlySales: 502,
    },
  },
  {
    id: 27,
    group_id: 25,
    name: '그레이 믹스 숄 칼라 가디건',
    colorId: 19,
    category: { parent: 'outer', current: 'cardigan' },
    price: 135000,
    thumbnailImage: 'cardigan-6.png',
    detailImages: ['cardigan-6.png'],
    createdAt: new Date('2026-04-02'),
    variants: [
      { id: '25-GMX-S', size: 'S', stock: 6, price_offset: 0 },
      { id: '25-GMX-M', size: 'M', stock: 9, price_offset: 0 },
      { id: '25-GMX-L', size: 'L', stock: 12, price_offset: 0 },
      { id: '25-GMX-XL', size: 'XL', stock: 4, price_offset: 3000 },
      { id: '25-GMX-2XL', size: '2XL', stock: 2, price_offset: 6000 },
    ],
    state: 'active',
    productStats: {
      totalSales: 1056,
      toDaySales: 6,
      weeklySales: 48,
      monthlySales: 189,
    },
  },
];
